./phosim instance_files/system0.instance -c trim.txt -w workdir/work0 -o outdir/out0
./phosim instance_files/system10.instance -c trim.txt -w workdir/work1 -o outdir/out1
./phosim instance_files/system100.instance -c trim.txt -w workdir/work2 -o outdir/out2
./phosim instance_files/system102.instance -c trim.txt -w workdir/work3 -o outdir/out3
./phosim instance_files/system104.instance -c trim.txt -w workdir/work4 -o outdir/out4
./phosim instance_files/system106.instance -c trim.txt -w workdir/work5 -o outdir/out5
./phosim instance_files/system108.instance -c trim.txt -w workdir/work6 -o outdir/out6
./phosim instance_files/system109.instance -c trim.txt -w workdir/work7 -o outdir/out7
./phosim instance_files/system111.instance -c trim.txt -w workdir/work8 -o outdir/out8
./phosim instance_files/system113.instance -c trim.txt -w workdir/work9 -o outdir/out9
./phosim instance_files/system114.instance -c trim.txt -w workdir/work10 -o outdir/out10
./phosim instance_files/system115.instance -c trim.txt -w workdir/work11 -o outdir/out11
./phosim instance_files/system116.instance -c trim.txt -w workdir/work12 -o outdir/out12
./phosim instance_files/system117.instance -c trim.txt -w workdir/work13 -o outdir/out13
./phosim instance_files/system118.instance -c trim.txt -w workdir/work14 -o outdir/out14
./phosim instance_files/system119.instance -c trim.txt -w workdir/work15 -o outdir/out15
./phosim instance_files/system12.instance -c trim.txt -w workdir/work16 -o outdir/out16
./phosim instance_files/system120.instance -c trim.txt -w workdir/work17 -o outdir/out17
./phosim instance_files/system121.instance -c trim.txt -w workdir/work18 -o outdir/out18
./phosim instance_files/system123.instance -c trim.txt -w workdir/work19 -o outdir/out19
./phosim instance_files/system124.instance -c trim.txt -w workdir/work20 -o outdir/out20
./phosim instance_files/system125.instance -c trim.txt -w workdir/work21 -o outdir/out21
./phosim instance_files/system126.instance -c trim.txt -w workdir/work22 -o outdir/out22
./phosim instance_files/system128.instance -c trim.txt -w workdir/work23 -o outdir/out23
./phosim instance_files/system130.instance -c trim.txt -w workdir/work24 -o outdir/out24
./phosim instance_files/system132.instance -c trim.txt -w workdir/work25 -o outdir/out25
./phosim instance_files/system134.instance -c trim.txt -w workdir/work26 -o outdir/out26
./phosim instance_files/system136.instance -c trim.txt -w workdir/work27 -o outdir/out27
./phosim instance_files/system138.instance -c trim.txt -w workdir/work28 -o outdir/out28
./phosim instance_files/system14.instance -c trim.txt -w workdir/work29 -o outdir/out29
./phosim instance_files/system140.instance -c trim.txt -w workdir/work30 -o outdir/out30
./phosim instance_files/system142.instance -c trim.txt -w workdir/work31 -o outdir/out31
./phosim instance_files/system144.instance -c trim.txt -w workdir/work32 -o outdir/out32
./phosim instance_files/system146.instance -c trim.txt -w workdir/work33 -o outdir/out33
./phosim instance_files/system148.instance -c trim.txt -w workdir/work34 -o outdir/out34
./phosim instance_files/system150.instance -c trim.txt -w workdir/work35 -o outdir/out35
./phosim instance_files/system152.instance -c trim.txt -w workdir/work36 -o outdir/out36
./phosim instance_files/system154.instance -c trim.txt -w workdir/work37 -o outdir/out37
./phosim instance_files/system156.instance -c trim.txt -w workdir/work38 -o outdir/out38
./phosim instance_files/system157.instance -c trim.txt -w workdir/work39 -o outdir/out39
./phosim instance_files/system159.instance -c trim.txt -w workdir/work40 -o outdir/out40
./phosim instance_files/system16.instance -c trim.txt -w workdir/work41 -o outdir/out41
./phosim instance_files/system161.instance -c trim.txt -w workdir/work42 -o outdir/out42
./phosim instance_files/system163.instance -c trim.txt -w workdir/work43 -o outdir/out43
./phosim instance_files/system165.instance -c trim.txt -w workdir/work44 -o outdir/out44
./phosim instance_files/system167.instance -c trim.txt -w workdir/work45 -o outdir/out45
./phosim instance_files/system169.instance -c trim.txt -w workdir/work46 -o outdir/out46
./phosim instance_files/system171.instance -c trim.txt -w workdir/work47 -o outdir/out47
./phosim instance_files/system173.instance -c trim.txt -w workdir/work48 -o outdir/out48
./phosim instance_files/system175.instance -c trim.txt -w workdir/work49 -o outdir/out49
./phosim instance_files/system177.instance -c trim.txt -w workdir/work50 -o outdir/out50
./phosim instance_files/system179.instance -c trim.txt -w workdir/work51 -o outdir/out51
./phosim instance_files/system18.instance -c trim.txt -w workdir/work52 -o outdir/out52
./phosim instance_files/system181.instance -c trim.txt -w workdir/work53 -o outdir/out53
./phosim instance_files/system182.instance -c trim.txt -w workdir/work54 -o outdir/out54
./phosim instance_files/system183.instance -c trim.txt -w workdir/work55 -o outdir/out55
./phosim instance_files/system184.instance -c trim.txt -w workdir/work56 -o outdir/out56
./phosim instance_files/system185.instance -c trim.txt -w workdir/work57 -o outdir/out57
./phosim instance_files/system187.instance -c trim.txt -w workdir/work58 -o outdir/out58
./phosim instance_files/system189.instance -c trim.txt -w workdir/work59 -o outdir/out59
./phosim instance_files/system191.instance -c trim.txt -w workdir/work60 -o outdir/out60
./phosim instance_files/system193.instance -c trim.txt -w workdir/work61 -o outdir/out61
./phosim instance_files/system195.instance -c trim.txt -w workdir/work62 -o outdir/out62
./phosim instance_files/system197.instance -c trim.txt -w workdir/work63 -o outdir/out63
./phosim instance_files/system199.instance -c trim.txt -w workdir/work64 -o outdir/out64
./phosim instance_files/system2.instance -c trim.txt -w workdir/work65 -o outdir/out65
./phosim instance_files/system20.instance -c trim.txt -w workdir/work66 -o outdir/out66
./phosim instance_files/system201.instance -c trim.txt -w workdir/work67 -o outdir/out67
./phosim instance_files/system203.instance -c trim.txt -w workdir/work68 -o outdir/out68
./phosim instance_files/system205.instance -c trim.txt -w workdir/work69 -o outdir/out69
./phosim instance_files/system207.instance -c trim.txt -w workdir/work70 -o outdir/out70
./phosim instance_files/system209.instance -c trim.txt -w workdir/work71 -o outdir/out71
./phosim instance_files/system210.instance -c trim.txt -w workdir/work72 -o outdir/out72
./phosim instance_files/system211.instance -c trim.txt -w workdir/work73 -o outdir/out73
./phosim instance_files/system213.instance -c trim.txt -w workdir/work74 -o outdir/out74
./phosim instance_files/system215.instance -c trim.txt -w workdir/work75 -o outdir/out75
./phosim instance_files/system217.instance -c trim.txt -w workdir/work76 -o outdir/out76
./phosim instance_files/system219.instance -c trim.txt -w workdir/work77 -o outdir/out77
./phosim instance_files/system22.instance -c trim.txt -w workdir/work78 -o outdir/out78
./phosim instance_files/system221.instance -c trim.txt -w workdir/work79 -o outdir/out79
./phosim instance_files/system223.instance -c trim.txt -w workdir/work80 -o outdir/out80
./phosim instance_files/system225.instance -c trim.txt -w workdir/work81 -o outdir/out81
./phosim instance_files/system227.instance -c trim.txt -w workdir/work82 -o outdir/out82
./phosim instance_files/system229.instance -c trim.txt -w workdir/work83 -o outdir/out83
./phosim instance_files/system23.instance -c trim.txt -w workdir/work84 -o outdir/out84
./phosim instance_files/system230.instance -c trim.txt -w workdir/work85 -o outdir/out85
./phosim instance_files/system232.instance -c trim.txt -w workdir/work86 -o outdir/out86
./phosim instance_files/system234.instance -c trim.txt -w workdir/work87 -o outdir/out87
./phosim instance_files/system236.instance -c trim.txt -w workdir/work88 -o outdir/out88
./phosim instance_files/system237.instance -c trim.txt -w workdir/work89 -o outdir/out89
./phosim instance_files/system239.instance -c trim.txt -w workdir/work90 -o outdir/out90
./phosim instance_files/system24.instance -c trim.txt -w workdir/work91 -o outdir/out91
./phosim instance_files/system241.instance -c trim.txt -w workdir/work92 -o outdir/out92
./phosim instance_files/system243.instance -c trim.txt -w workdir/work93 -o outdir/out93
./phosim instance_files/system245.instance -c trim.txt -w workdir/work94 -o outdir/out94
./phosim instance_files/system246.instance -c trim.txt -w workdir/work95 -o outdir/out95
./phosim instance_files/system247.instance -c trim.txt -w workdir/work96 -o outdir/out96
./phosim instance_files/system248.instance -c trim.txt -w workdir/work97 -o outdir/out97
./phosim instance_files/system250.instance -c trim.txt -w workdir/work98 -o outdir/out98
./phosim instance_files/system252.instance -c trim.txt -w workdir/work99 -o outdir/out99
./phosim instance_files/system254.instance -c trim.txt -w workdir/work100 -o outdir/out100
./phosim instance_files/system256.instance -c trim.txt -w workdir/work101 -o outdir/out101
./phosim instance_files/system258.instance -c trim.txt -w workdir/work102 -o outdir/out102
./phosim instance_files/system26.instance -c trim.txt -w workdir/work103 -o outdir/out103
./phosim instance_files/system260.instance -c trim.txt -w workdir/work104 -o outdir/out104
./phosim instance_files/system262.instance -c trim.txt -w workdir/work105 -o outdir/out105
./phosim instance_files/system264.instance -c trim.txt -w workdir/work106 -o outdir/out106
./phosim instance_files/system266.instance -c trim.txt -w workdir/work107 -o outdir/out107
./phosim instance_files/system268.instance -c trim.txt -w workdir/work108 -o outdir/out108
./phosim instance_files/system270.instance -c trim.txt -w workdir/work109 -o outdir/out109
./phosim instance_files/system272.instance -c trim.txt -w workdir/work110 -o outdir/out110
./phosim instance_files/system274.instance -c trim.txt -w workdir/work111 -o outdir/out111
./phosim instance_files/system276.instance -c trim.txt -w workdir/work112 -o outdir/out112
./phosim instance_files/system278.instance -c trim.txt -w workdir/work113 -o outdir/out113
./phosim instance_files/system28.instance -c trim.txt -w workdir/work114 -o outdir/out114
./phosim instance_files/system280.instance -c trim.txt -w workdir/work115 -o outdir/out115
./phosim instance_files/system282.instance -c trim.txt -w workdir/work116 -o outdir/out116
./phosim instance_files/system284.instance -c trim.txt -w workdir/work117 -o outdir/out117
./phosim instance_files/system286.instance -c trim.txt -w workdir/work118 -o outdir/out118
./phosim instance_files/system288.instance -c trim.txt -w workdir/work119 -o outdir/out119
./phosim instance_files/system29.instance -c trim.txt -w workdir/work120 -o outdir/out120
./phosim instance_files/system290.instance -c trim.txt -w workdir/work121 -o outdir/out121
./phosim instance_files/system292.instance -c trim.txt -w workdir/work122 -o outdir/out122
./phosim instance_files/system294.instance -c trim.txt -w workdir/work123 -o outdir/out123
./phosim instance_files/system296.instance -c trim.txt -w workdir/work124 -o outdir/out124
./phosim instance_files/system297.instance -c trim.txt -w workdir/work125 -o outdir/out125
./phosim instance_files/system299.instance -c trim.txt -w workdir/work126 -o outdir/out126
./phosim instance_files/system301.instance -c trim.txt -w workdir/work127 -o outdir/out127
./phosim instance_files/system303.instance -c trim.txt -w workdir/work128 -o outdir/out128
./phosim instance_files/system305.instance -c trim.txt -w workdir/work129 -o outdir/out129
./phosim instance_files/system307.instance -c trim.txt -w workdir/work130 -o outdir/out130
./phosim instance_files/system309.instance -c trim.txt -w workdir/work131 -o outdir/out131
./phosim instance_files/system31.instance -c trim.txt -w workdir/work132 -o outdir/out132
./phosim instance_files/system311.instance -c trim.txt -w workdir/work133 -o outdir/out133
./phosim instance_files/system313.instance -c trim.txt -w workdir/work134 -o outdir/out134
./phosim instance_files/system315.instance -c trim.txt -w workdir/work135 -o outdir/out135
./phosim instance_files/system316.instance -c trim.txt -w workdir/work136 -o outdir/out136
./phosim instance_files/system318.instance -c trim.txt -w workdir/work137 -o outdir/out137
./phosim instance_files/system320.instance -c trim.txt -w workdir/work138 -o outdir/out138
./phosim instance_files/system322.instance -c trim.txt -w workdir/work139 -o outdir/out139
./phosim instance_files/system324.instance -c trim.txt -w workdir/work140 -o outdir/out140
./phosim instance_files/system326.instance -c trim.txt -w workdir/work141 -o outdir/out141
./phosim instance_files/system328.instance -c trim.txt -w workdir/work142 -o outdir/out142
./phosim instance_files/system33.instance -c trim.txt -w workdir/work143 -o outdir/out143
./phosim instance_files/system330.instance -c trim.txt -w workdir/work144 -o outdir/out144
./phosim instance_files/system332.instance -c trim.txt -w workdir/work145 -o outdir/out145
./phosim instance_files/system334.instance -c trim.txt -w workdir/work146 -o outdir/out146
./phosim instance_files/system336.instance -c trim.txt -w workdir/work147 -o outdir/out147
./phosim instance_files/system338.instance -c trim.txt -w workdir/work148 -o outdir/out148
./phosim instance_files/system34.instance -c trim.txt -w workdir/work149 -o outdir/out149
./phosim instance_files/system340.instance -c trim.txt -w workdir/work150 -o outdir/out150
./phosim instance_files/system342.instance -c trim.txt -w workdir/work151 -o outdir/out151
./phosim instance_files/system344.instance -c trim.txt -w workdir/work152 -o outdir/out152
./phosim instance_files/system346.instance -c trim.txt -w workdir/work153 -o outdir/out153
./phosim instance_files/system348.instance -c trim.txt -w workdir/work154 -o outdir/out154
./phosim instance_files/system350.instance -c trim.txt -w workdir/work155 -o outdir/out155
./phosim instance_files/system352.instance -c trim.txt -w workdir/work156 -o outdir/out156
./phosim instance_files/system36.instance -c trim.txt -w workdir/work157 -o outdir/out157
./phosim instance_files/system38.instance -c trim.txt -w workdir/work158 -o outdir/out158
./phosim instance_files/system4.instance -c trim.txt -w workdir/work159 -o outdir/out159
./phosim instance_files/system40.instance -c trim.txt -w workdir/work160 -o outdir/out160
./phosim instance_files/system42.instance -c trim.txt -w workdir/work161 -o outdir/out161
./phosim instance_files/system44.instance -c trim.txt -w workdir/work162 -o outdir/out162
./phosim instance_files/system46.instance -c trim.txt -w workdir/work163 -o outdir/out163
./phosim instance_files/system48.instance -c trim.txt -w workdir/work164 -o outdir/out164
./phosim instance_files/system5.instance -c trim.txt -w workdir/work165 -o outdir/out165
./phosim instance_files/system50.instance -c trim.txt -w workdir/work166 -o outdir/out166
./phosim instance_files/system52.instance -c trim.txt -w workdir/work167 -o outdir/out167
./phosim instance_files/system54.instance -c trim.txt -w workdir/work168 -o outdir/out168
./phosim instance_files/system56.instance -c trim.txt -w workdir/work169 -o outdir/out169
./phosim instance_files/system58.instance -c trim.txt -w workdir/work170 -o outdir/out170
./phosim instance_files/system6.instance -c trim.txt -w workdir/work171 -o outdir/out171
./phosim instance_files/system60.instance -c trim.txt -w workdir/work172 -o outdir/out172
./phosim instance_files/system62.instance -c trim.txt -w workdir/work173 -o outdir/out173
./phosim instance_files/system64.instance -c trim.txt -w workdir/work174 -o outdir/out174
./phosim instance_files/system66.instance -c trim.txt -w workdir/work175 -o outdir/out175
./phosim instance_files/system68.instance -c trim.txt -w workdir/work176 -o outdir/out176
./phosim instance_files/system7.instance -c trim.txt -w workdir/work177 -o outdir/out177
./phosim instance_files/system70.instance -c trim.txt -w workdir/work178 -o outdir/out178
./phosim instance_files/system71.instance -c trim.txt -w workdir/work179 -o outdir/out179
./phosim instance_files/system73.instance -c trim.txt -w workdir/work180 -o outdir/out180
./phosim instance_files/system75.instance -c trim.txt -w workdir/work181 -o outdir/out181
./phosim instance_files/system76.instance -c trim.txt -w workdir/work182 -o outdir/out182
./phosim instance_files/system78.instance -c trim.txt -w workdir/work183 -o outdir/out183
./phosim instance_files/system80.instance -c trim.txt -w workdir/work184 -o outdir/out184
./phosim instance_files/system82.instance -c trim.txt -w workdir/work185 -o outdir/out185
./phosim instance_files/system84.instance -c trim.txt -w workdir/work186 -o outdir/out186
./phosim instance_files/system86.instance -c trim.txt -w workdir/work187 -o outdir/out187
./phosim instance_files/system87.instance -c trim.txt -w workdir/work188 -o outdir/out188
./phosim instance_files/system88.instance -c trim.txt -w workdir/work189 -o outdir/out189
./phosim instance_files/system9.instance -c trim.txt -w workdir/work190 -o outdir/out190
./phosim instance_files/system90.instance -c trim.txt -w workdir/work191 -o outdir/out191
./phosim instance_files/system92.instance -c trim.txt -w workdir/work192 -o outdir/out192
./phosim instance_files/system93.instance -c trim.txt -w workdir/work193 -o outdir/out193
./phosim instance_files/system95.instance -c trim.txt -w workdir/work194 -o outdir/out194
./phosim instance_files/system97.instance -c trim.txt -w workdir/work195 -o outdir/out195
./phosim instance_files/system98.instance -c trim.txt -w workdir/work196 -o outdir/out196
./phosim instance_files/system99.instance -c trim.txt -w workdir/work197 -o outdir/out197
